# Generated by Django 4.0.2 on 2022-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cykl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.IntegerField(default=0)),
                ('in_time', models.IntegerField(default=-1)),
                ('out_time', models.IntegerField(default=-1)),
                ('no_rides', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='cykl_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('no_rides_used', models.IntegerField(default=0)),
            ],
        ),
    ]
