# Generated by Django 4.0.2 on 2022-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cykl', '0002_remove_cykl_users_username_cykl_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cykl',
            name='present_at',
            field=models.IntegerField(default=-1),
        ),
    ]
