# Generated by Django 4.0.2 on 2022-02-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cykl', '0005_alter_cykl_managers_alter_cykl_users_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cykl_users',
        ),
    ]
